spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.99.101
          jwk-set-uri: http://192.168.99.101/oauth/discovery/keys

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:debugee
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

server:
  error:
    include-binding-errors: always

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        sql: ERROR
        type: ERROR
    htrcak:
      backend: debug

cors:
  allowed-origins: http://localhost:4200,http://127.0.0.1:4200

gitlab:
  uri: http://192.168.99.101
  client-id: 7bb581ae9321027b75d59f9b35a7963255dc42ad3ce8a6e4647d0259b26713dc
  callback-url: http://192.168.0.212:8080/callback/gitlab
  web-url: http://127.0.0.1:4200

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:debugee_test;DB_CLOSE_DELAY=-1

---
spring:
  config:
    activate:
      on-profile: prod

cors:
  allowed-origins: http://20.82.136.123,https://debugee.live

gitlab:
  uri: http://164.90.165.32
  client-id: 4aaa243bf068dd1c42616d15d555e394d9a76cc51ca9d2fac4af89ce5e035a10
  callback-url: http://20.82.136.123/callback/gitlab
  web-url: http://20.82.136.123