spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.99.101
          jwk-set-uri: http://192.168.99.101/oauth/discovery/keys

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:h2:mem:hardware
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
